name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]
    defaults:
      run:
        working-directory: ./example-app
    steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
            python-version: "3.10"
        - name: Install Poetry Action
          uses: snok/install-poetry@v1.3.4
          with:
            virtualenvs-create: true
            virtualenvs-in-project: false
            installer-parallel: true
        - name: Install dependencies
          run: |
           poetry install --no-root
        - name: Cache build venv
          id: cached-poetry-dependencies
          uses: actions/cache@v3
          with:
            path: /home/runner/.cache/pypoetry/virtualenvs
            key: ${{ runner.os }}-venv
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]
    defaults:
      run:
        working-directory: ./example-app
    needs: build
    steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
            python-version: "3.10"
        - name: Install Poetry Action
          uses: snok/install-poetry@v1.3.4
          with:
            virtualenvs-create: true
            virtualenvs-in-project: false
            installer-parallel: true
        - name: Cache build venv
          id: cached-poetry-dependencies
          uses: actions/cache@v3
          with:
            path: /home/runner/.cache/pypoetry/virtualenvs
            key: ${{ runner.os }}-venv
        - name: Poetry lint
          run: |
            poetry run task lint
  formatter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]
    defaults:
      run:
        working-directory: ./example-app
    needs: build
    steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
            python-version: "3.10"
        - name: Install Poetry Action
          uses: snok/install-poetry@v1.3.4
          with:
            virtualenvs-create: true
            virtualenvs-in-project: false
            installer-parallel: true
        - name: Cache build venv
          id: cached-poetry-dependencies
          uses: actions/cache@v3
          with:
            path: /home/runner/.cache/pypoetry/virtualenvs
            key: ${{ runner.os }}-venv
        - name: Poetry formatter
          run: |
            poetry run task formatter
  security:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]
    defaults:
      run:
        working-directory: ./example-app
    needs: build
    steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
            python-version: "3.10"
        - name: Install Poetry Action
          uses: snok/install-poetry@v1.3.4
          with:
            virtualenvs-create: true
            virtualenvs-in-project: false
            installer-parallel: true
        - name: Cache build venv
          id: cached-poetry-dependencies
          uses: actions/cache@v3
          with:
            path: /home/runner/.cache/pypoetry/virtualenvs
            key: ${{ runner.os }}-venv
        - name: Poetry security
          run: |
            poetry run task security
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]
    defaults:
      run:
        working-directory: ./example-app
    needs: [build, lint, formatter, security]
    steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
            python-version: "3.10"
        - name: Install Poetry Action
          uses: snok/install-poetry@v1.3.4
          with:
            virtualenvs-create: true
            virtualenvs-in-project: false
            installer-parallel: true
        - name: Cache build venv
          id: cached-poetry-dependencies
          uses: actions/cache@v3
          with:
            path: /home/runner/.cache/pypoetry/virtualenvs
            key: ${{ runner.os }}-venv
        - name: Poetry test
          run: |
            poetry run task test

    
